export const ICONS = {
  book: [
    ".kkkkkk.",
    "knnnnnlk",
    "knwwwnlk",
    "knnnnnlk",
    "knwwwnlk",
    "knnnnnlk",
    "kgggggGk",
    ".kkkkkk.",
  ],
  search: [
    ".kkkk...",
    "kbwbbk..",
    "kwbbbk..",
    "kbbbbk..",
    ".kkkkk..",
    "....kpk.",
    ".....kpk",
    "......kk",
  ],
  castle: [
    "k.k..k.k",
    "kskssksk",
    "kssssssk",
    "kssppssk",
    "kssppssk",
    "kssppssk",
    "kssppssk",
    "kkkkkkkk",
  ],
  rupee: [
    "...kk...",
    "..kllk..",
    ".kllwlk.",
    "kllwlllk",
    "kllwllnk",
    ".kllllk.",
    "..kllk..",
    "...kk...",
  ],
  lock: [
    "..kkkk..",
    ".kGGGGk.",
    ".kG..Gk.",
    "kkkkkkkk",
    "kggggggk",
    "kggkkggk",
    "kggkkggk",
    "kkkkkkkk",
  ],
  python: [
    ".kkkk...",
    "kbwbbk..",
    "kbbbbkkk",
    "kbbkkggk",
    "kkkggggk",
    "..kggwgk",
    "..kgggk.",
    "...kkkk.",
  ],
  team: [
    ".kk..kk.",
    "kwwkkwwk",
    ".kk..kk.",
    "kggkkbbk",
    "kggkkbbk",
    "kggkkbbk",
    "kggkkbbk",
    "kkkkkkkk",
  ],
  english: [
    "..kkkk..",
    ".kbblbk.",
    "kbllbbbk",
    "kblbblbk",
    "kbbbllbk",
    "kbblllbk",
    ".kbbbbk.",
    "..kkkk..",
  ],
  git: [
    "...kk...",
    "..krrk..",
    ".kwgrrk.",
    "krrkrrrk",
    "krrkrwgk",
    ".krkrrk.",
    "..kwgk..",
    "...kk...",
  ],
  framework: [
    "..kkkk..",
    ".kllllk.",
    "kllwlllk",
    "kkkkkkkk",
    "kbbbbbbk",
    "kkkkkkkk",
    "kggggggk",
    "kkkkkkkk",
  ],
  ai: [
    "........",
    "gg....bb",
    "ggk..kbb",
    "..kwlk..",
    "..kllk..",
    "ggk..kbb",
    "gg....bb",
    "........",
  ],
};
